{
 "title": "NAS Units",
 "description": "This dashboard provides real-time and historical monitoring of the PiNAS (Huginn) and Vital NAS (Muninn) units. It tracks key system and storage metrics, ensuring smooth operation, early failure detection, and optimal performance for both NAS devices.",
 "tags": [
  "nas",
  "homelab",
  "storage",
  "grafana",
  "monitoring",
  "huginn",
  "muninn",
  "pinas",
  "truenas",
  "system-metrics",
  "networking",
  "alerts",
  "prometheus",
  "disk-usage",
  "cpu-usage",
  "memory",
  "uptime",
  "zfs",
  "raid",
  "smb",
  "nfs",
  "backup"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PiNAS - Huginn",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"} / node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "PiNAS (Huginn) - Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PiNAS (Huginn)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load over 1 minute" },
    { "expr": "node_load5", "legendFormat": "Load over 5 minutes" },
    { "expr": "node_load15", "legendFormat": "Load over 15 minutes" }
   ]
  },
  {
   "title": "VS NAS - Muninn",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"} / node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "VS NAS (Muninn) - Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VS NAS (Muninn)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load over 1 minute" },
    { "expr": "node_load5", "legendFormat": "Load over 5 minutes" },
    { "expr": "node_load15", "legendFormat": "Load over 15 minutes" }
   ]
  },
  {
   "title": "PiNAS (Huginn) - Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "VS NAS (Muninn) - Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "SD Card",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"mmcblk0\"}[1m])",
     "legendFormat": "Read Speed (MB/s)"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"mmcblk0\"}[1m])",
     "legendFormat": "Write Speed (MB/s)"
    }
   ]
  },
  {
   "title": "Large Array",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"md0\"}[1m])",
     "legendFormat": "Read Speed (MB/s)"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"md0\"}[1m])",
     "legendFormat": "Write Speed (MB/s)"
    }
   ]
  },
  {
   "title": "Fast Array",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"md1\"}[1m])",
     "legendFormat": "Read Speed (MB/s)"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"md1\"}[1m])",
     "legendFormat": "Write Speed (MB/s)"
    }
   ]
  },
  {
   "title": "Plex",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sdd\"}[1m])",
     "legendFormat": "Read Speed (MB/s)"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sdd\"}[1m])",
     "legendFormat": "Write Speed (MB/s)"
    }
   ]
  },
  {
   "title": "Downloads Folder",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sdd\"}[1m])",
     "legendFormat": "Read Speed (MB/s)"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sdd\"}[1m])",
     "legendFormat": "Write Speed (MB/s)"
    }
   ]
  },
  {
   "title": "User Folders",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sdd\"}[1m])",
     "legendFormat": "Read Speed (MB/s)"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sdd\"}[1m])",
     "legendFormat": "Write Speed (MB/s)"
    }
   ]
  },
  {
   "title": "Project Backups",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sdd\"}[1m])",
     "legendFormat": "Read Speed (MB/s)"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sdd\"}[1m])",
     "legendFormat": "Write Speed (MB/s)"
    }
   ]
  },
  {
   "title": "PiNAS (Huginn) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Memory Used"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Memory Free" }
   ]
  },
  {
   "title": "PiNAS (Huginn) - Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "Incoming Bandwidth"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "Outgoing Bandwidth"
    }
   ]
  },
  {
   "title": "VS NAS (Muninn) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Memory Used"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Memory Free" }
   ]
  },
  {
   "title": "VS NAS (Muninn) - Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "Incoming Bandwidth"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "Outgoing Bandwidth"
    }
   ]
  }
 ]
}