{
 "title": "internet connection",
 "tags": [
  "speedtest",
  "ping"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Download",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{instance=\"192.168.1.18:9798\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{instance=\"192.168.1.18:9798\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds{instance=\"192.168.1.18:9798\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_jitter_latency_milliseconds{instance=\"192.168.1.18:9798\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internet Jitter/Latency & Ping",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "speedtest_jitter_latency_milliseconds{instance=\"192.168.1.18:9798\"}",
     "legendFormat": "Jitter/Latency"
    },
    {
     "expr": "speedtest_ping_latency_milliseconds{instance=\"192.168.1.18:9798\"}",
     "legendFormat": "Ping"
    }
   ]
  },
  {
   "title": "Internet Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "speedtest_up{instance=\"192.168.1.18:9798\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=\"http://github.com\"})",
     "legendFormat": "Internet Connection"
    }
   ]
  }
 ]
}