{
 "title": "PotentPi Dashboard",
 "description": "This dashboard provides real-time and historical insights into the health and performance of the 5 Raspberry Pi nodes in the homelab cluster. It visualizes key hardware metrics to detect potential issues, optimize performance, and ensure system stability.",
 "tags": [
  "raspberry-pi",
  "homelab",
  "monitoring",
  "grafana",
  "hardware-health",
  "pi-cluster",
  "system-metrics",
  "performance",
  "networking",
  "alerts",
  "prometheus",
  "telegraf",
  "influxdb",
  "temperature",
  "disk-usage",
  "cpu-usage",
  "memory",
  "uptime",
  "systemd",
  "throttling"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Potent Pi 1 - Odin",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"} / node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 2 - Mimir",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " 100 - (avg by(instance) (irate(node_cpu_seconds_total{job=\"nodeexp\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{job=\"nodeexp\"} / node_memory_MemTotal_bytes{job=\"nodeexp\"}))",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"nodeexp\",mountpoint=\"/\"} / node_filesystem_avail_bytes{job=\"nodeexp\",mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{job=\"nodeexp\",device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{job=\"nodeexp\",device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 3 - Loki",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"} / node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 4 - Midgard",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"} / node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 5 - Frigg",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{job=\"homeassistant\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{job=\"homeassistant\"} / node_memory_MemTotal_bytes{job=\"homeassistant\"}))",
     "legendFormat": "MEM Usage"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"homeassistant\", mountpoint=\"/\"} / node_filesystem_avail_bytes{job=\"homeassistant\", mountpoint=\"/\"}",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{job=\"homeassistant\", device=\"hassio\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{job=\"homeassistant\", device=\"hassio\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization"
    }
   ]
  },
  {
   "title": "Potent Pi 1  (Odin) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Memory Used"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Memory Free" }
   ]
  },
  {
   "title": "Potent Pi 1 (Odin)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load over 1 minute" },
    { "expr": "node_load5", "legendFormat": "Load over 5 minutes" },
    { "expr": "node_load15", "legendFormat": "Load over 15 minutes" }
   ]
  },
  {
   "title": "Potent Pi 2 (Mimir) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"nodeexp\"} - node_memory_MemAvailable_bytes{job=\"nodeexp\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"nodeexp\"}",
     "legendFormat": "Memory Free"
    }
   ]
  },
  {
   "title": "Potent Pi 2 (Mimir)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexp\"}",
     "legendFormat": "Load over 1 minute"
    },
    {
     "expr": "node_load5{job=\"nodeexp\"}",
     "legendFormat": "Load over 5 minutes"
    },
    {
     "expr": "node_load15{job=\"nodeexp\"}",
     "legendFormat": "Load over 15 minutes"
    }
   ]
  },
  {
   "title": "Potent Pi 3 (Loki) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Memory Used"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Memory Free" }
   ]
  },
  {
   "title": "Potent Pi 3 (Loki)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load over 1 minute" },
    { "expr": "node_load5", "legendFormat": "Load over 5 minutes" },
    { "expr": "node_load15", "legendFormat": "Load over 15 minutes" }
   ]
  },
  {
   "title": "Potent Pi 4 (Midgard) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Memory Used"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Memory Free" }
   ]
  },
  {
   "title": "Potent Pi 4 (Midgard)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 17, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load over 1 minute" },
    { "expr": "node_load5", "legendFormat": "Load over 5 minutes" },
    { "expr": "node_load15", "legendFormat": "Load over 15 minutes" }
   ]
  },
  {
   "title": "Potent Pi 5 (Frigg) - MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"homeassistant\"} - node_memory_MemAvailable_bytes{job=\"homeassistant\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"homeassistant\"}",
     "legendFormat": "Memory Free"
    }
   ]
  },
  {
   "title": "Potent Pi 5 (Frigg)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"homeassistant\"}",
     "legendFormat": "Load over 1 minute"
    },
    {
     "expr": "node_load5{job=\"homeassistant\"}",
     "legendFormat": "Load over 5 minutes"
    },
    {
     "expr": "node_load15{job=\"homeassistant\"}",
     "legendFormat": "Load over 15 minutes"
    }
   ]
  },
  {
   "title": "Potent Pi 1 (Odin) - Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 2 (Mimir) - Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"nodeexp\", sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 3 (Loki) - Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 4 (Midgard) - Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 5 (Frigg) - Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"homeassistant\", sensor=\"temp0\"}",
     "legendFormat": "Temperature (°C)"
    }
   ]
  },
  {
   "title": "Potent Pi 1 (Odin) - Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 2 (Mimir) - Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"nodeexp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 3 (Loki) - Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 4 (Midgard) - Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 5 (Frigg) - Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"homeassistant\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potent Pi 1 (Odin) - Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "Incoming Bandwidth"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "Outgoing Bandwidth"
    }
   ]
  },
  {
   "title": "Potent Pi 2 (Mimir) - Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"nodeexp\",device=\"eth0\"}[1m])",
     "legendFormat": "Incoming Bandwidth"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"nodeexp\",device=\"eth0\"}[1m])",
     "legendFormat": "Outgoing Bandwidth"
    }
   ]
  },
  {
   "title": "Potent Pi 3 (Loki) - Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "Incoming Bandwidth"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "Outgoing Bandwidth"
    }
   ]
  },
  {
   "title": "Potent Pi 4 (Midgard) - Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "Incoming Bandwidth"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "Outgoing Bandwidth"
    }
   ]
  },
  {
   "title": "Potent Pi 5 (Frigg) - Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"homeassistant\", device=\"hassio\"}[1m])",
     "legendFormat": "Incoming Bandwidth"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"homeassistant\", device=\"hassio\"}[1m])",
     "legendFormat": "Outgoing Bandwidth"
    }
   ]
  }
 ]
}