{
 "title": "PfSense Router",
 "description": "This dashboard provides a comprehensive view of the performance and activity of your pfSense router. Designed with multiple VLANs in mind, it monitors key metrics like network traffic, interface status, CPU and memory usage, and firewall events. Each VLAN is tracked individually to provide insights into traffic patterns, device behavior, and bandwidth utilization.\n\nKey Features:\n\nReal-time and historical data visualization for all VLANs\nTraffic analysis by VLAN and interface\nFirewall logs and alerts\nResource usage (CPU, memory, disk)\nWAN connection performance and latency monitoring",
 "tags": [
  "System Performance",
  "Traffic Analysis",
  "Bandwidth",
  "Metrics",
  "Firewall",
  "Dashboard",
  "Monitoring",
  "Networking",
  "VLAN",
  "Router",
  "pfSense"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(irate(node_cpu_seconds_total{job=\"prometheus-router\",mode=\"idle\"}[5m])) by (instance))",
     "legendFormat": "CPU Usage (%)"
    },
    {
     "expr": "100 * (node_memory_size_bytes{job=\"prometheus-router\"} - (node_memory_free_bytes{job=\"prometheus-router\"} + node_memory_buffer_bytes{job=\"prometheus-router\"} + node_memory_cache_bytes{job=\"prometheus-router\"} + node_memory_inactive_bytes{job=\"prometheus-router\"} + node_memory_laundry_bytes{job=\"prometheus-router\"})) / node_memory_size_bytes{job=\"prometheus-router\"}",
     "legendFormat": "MEM Usage (%)"
    },
    {
     "expr": "100 * (node_filesystem_size_bytes{job=\"prometheus-router\",mountpoint=\"/\"} - node_filesystem_free_bytes{job=\"prometheus-router\",mountpoint=\"/\"}) / node_filesystem_size_bytes{job=\"prometheus-router\",mountpoint=\"/\"}",
     "legendFormat": "Disk Usage (%)"
    },
    {
     "expr": "100 * (irate(node_network_receive_bytes_total{job=\"prometheus-router\",device=\"re0\"}[10m]) * 8) / 1000000000",
     "legendFormat": "Incoming Network Utilization (1Gb Link)"
    },
    {
     "expr": "100 * (irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re0\"}[1m]) * 8) / 1000000000",
     "legendFormat": "Outgoing Network Utilization (1Gb Link)"
    }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_size_bytes{job=\"prometheus-router\"} - (node_memory_free_bytes{job=\"prometheus-router\"} + node_memory_buffer_bytes{job=\"prometheus-router\"} + node_memory_cache_bytes{job=\"prometheus-router\"} + node_memory_inactive_bytes{job=\"prometheus-router\"} + node_memory_laundry_bytes{job=\"prometheus-router\"})\r\n",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "node_memory_free_bytes{job=\"prometheus-router\"}",
     "legendFormat": "Memory Free"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"prometheus-router\"}",
     "legendFormat": "Load over 1 minute"
    },
    {
     "expr": "node_load5{job=\"prometheus-router\"}",
     "legendFormat": "Load over 5 minutes"
    },
    {
     "expr": "node_load15{job=\"prometheus-router\"}",
     "legendFormat": "Load over 15 minutes"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"prometheus-router\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VLAN Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus-router\",device=\"re1.1\"}[1m]) * 8",
     "legendFormat": "Incoming (VLAN 1)"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re1.1\"}[1m]) * 8) * -1",
     "legendFormat": "Outgoing (VLAN 1)"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus-router\",device=\"re1.10\"}[1m]) * 8",
     "legendFormat": "Incoming (VLAN 10)"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re1.10\"}[1m]) * 8) * -1",
     "legendFormat": "Outgoing (VLAN 10)"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus-router\",device=\"re1.25\"}[1m]) * 8",
     "legendFormat": "Incoming (VLAN 10)"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re1.25\"}[1m]) * 8) * -1",
     "legendFormat": "Outgoing (VLAN 10)"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus-router\",device=\"re1.99\"}[1m]) * 8",
     "legendFormat": "Incoming (VLAN 99)"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re1.99\"}[1m]) * 8) * -1",
     "legendFormat": "Outgoing (VLAN 99)"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus-router\",device=\"re1.100\"}[1m]) * 8",
     "legendFormat": "Incoming (VLAN 100)"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re1.100\"}[1m]) * 8) * -1",
     "legendFormat": "Outgoing (VLAN 100)"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus-router\",device=\"re1.1000\"}[1m]) * 8",
     "legendFormat": "Incoming (VLAN 1000)"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re1.1000\"}[1m]) * 8) * -1",
     "legendFormat": "Outgoing (VLAN 1000)"
    }
   ]
  },
  {
   "title": "WAN Traffic & Bandwidth Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus-router\",device=\"re0\"}[1m]) * 8",
     "legendFormat": "Incoming (WAN)"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{job=\"prometheus-router\",device=\"re0\"}[1m]) * 8) * -1",
     "legendFormat": "Outgoing (WAN)"
    }
   ]
  }
 ]
}