services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
    - /home/${USER}/pp2-mimir/docker/uptime-kuma/data:/app/data
    ports:
    - 3001:3001
    environment:
    - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=1
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
